version: '2'
services:
    ticketsharing-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ticketsharing/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ticketsharing
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
